version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: career-platform-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - career-platform-network
    command: npm start

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: career-platform-client
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: http://localhost:5000
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - career-platform-network
    command: npm run dev -- --host 0.0.0.0

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: career-platform-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - career-platform-network

networks:
  career-platform-network:
    driver: bridge